### PR TITLE
Add support for unsigned long long

### LINKED ISSUE #16: unsigned long long
Hi there,
I have a member of a model that I would like to use `unsigned long long` as the type, but compilation failed at `hiberlite::access::hibernate`'s `c.hibernate(a)` call because "Member reference base type 'unsigned long long' is not a structure or union".
I see that long long is allowed.

Is it possible to resolve this?
Also, is it possible to use enum and map it to an integer type for example? Thanks!

### PR DESCRIPTION
**Pull request by paulftw**
This should fix #16

### CODE REVIEW

**Comment by paulftw** [comment]
@d-led could you please take a look if this change makes sense? I'm not sure about the unsigned/signed conversion

**Comment by d-led** [comment]
`unsigned long long` is at [least 64bit](http://en.cppreference.com/w/cpp/language/types), but a quick search doesn't yield a platform, where this could be bigger, thus I'd say 64bit is ok. As for signedness, let's write a test. (can't do at the moment, will think about one in the evening)

**Comment by nirbadichi** [comment]
Thanks for the help!

**Comment by d-led** [comment]
first approach check if `ULLONG_MAX ` survives:

```c++
ull_t max = { ULLONG_MAX };
// struct to avoid compiler warning C4307
REQUIRE((max.v + 1) == 0);
bean_ptr<ull_t> id = db.copyBean(max);
bean_ptr<ull_t> max_new = db.loadBean<ull_t>(id);
CHECK(max_new->v == max.v);
```

didn't have time to make a runnable test yet

**Comment by d-led** [comment]
looks ok for me, since storing and retrieving the maximum value of unsigned long long works. If a platform that has a bigger ull comes around, it'll need a breaking change, but it's probably unlikely

**Pull request merged**
